version: "3.9"
services:
  api:
    container_name: user-management-api
    hostname: user-management-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TODO_ENV: dev
      PORT: 8080
      TODO_DB_HOST: user-management-db
      TODO_DB_PORT: 5432
      TODO_DB_USER: user_management
      TODO_DB_PASSWORD: user_management
      TODO_DB_NAME: user_management
    volumes:
      - .:/app
    ports:
      - "18000:8080"
    command: sleep infinity

  db:
    container_name: user-management-db
    hostname: user-management-db
    image: postgres
    platform: linux/amd64
    environment:
      POSTGRES_USER: user_management
      POSTGRES_PASSWORD: user_management
      POSTGRES_DB: user_management
    volumes:
      - postgres-data:/var/lib/postgresql/data
      # dockerコンテナ起動時に自動で実行される.sqlファイル
      - ./_tools/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5555:5432"

volumes:
  postgres-data: