name: test
on:
  push:
    branches:
      - "main"
  
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        ports:
          - 3306:3306
        env:
          POSTGRES_USER: user_management
          POSTGRES_PASSWORD: user_management
          POSTGRES_DB: user_management
        options: >-
          --health-cmd "pg_isready -U ${POSTGRES_USER}"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19'
      - uses: actions/checkout@v3
      
      - run: go test ./... -coverprofile=coverage.out

      - name: report coverage
        uses: k1LoW/octocov-action@v0